<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { apiGet, ApiClientError } from '@/api/client'
import ErrorState from '@/components/ErrorState.vue'
import LoadingState from '@/components/LoadingState.vue'
import { useAnalysisStore } from '@/stores/analysis'

interface Batch { batchId: string; sourceName: string; startedAt: string; completedAt: string | null; status: string; rawRowCount: number; normalizedRowCount: number; issueCount: number }
interface Issue { statementType: string; code: string | null; reportPeriod: string | null; fieldName: string; rawValue: string | null; issueCode: string; issueMessage: string; createdAt: string }
const store = useAnalysisStore(); const data = ref<{ batches: Batch[]; issues: Issue[] } | null>(null); const loading = ref(false); const error = ref<ApiClientError | null>(null)
async function load() { loading.value = true; error.value = null; try { data.value = await apiGet('/api/data-quality') } catch (cause) { error.value = cause as ApiClientError } finally { loading.value = false } }
onMounted(load)
</script>
<template>
  <section><header class="page-head"><div><h1 class="page-title">数据质量与追溯</h1><p class="page-intro">检查默认数据库路径、标准化覆盖、导入批次与字段解析异常。这里不生成虚构评分。</p></div><div class="status-line"><span class="status-dot" :class="{ warning: (store.meta?.qualityIssueCount ?? 0) > 0 }"></span><span>{{ store.meta?.qualityIssueCount ?? 0 }} 项质量记录</span></div></header>
    <section class="source-ledger panel"><div><span>DATABASE PATH</span><strong>{{ store.meta?.databasePath }}</strong></div><div><span>SCHEMA VERSION</span><strong>{{ store.meta?.schemaVersion }} / NORMALIZED</strong></div><div><span>INCOME</span><strong>{{ store.meta?.incomeStatementCount }} ROWS</strong></div><div><span>BALANCE</span><strong>{{ store.meta?.balanceSheetCount }} ROWS</strong></div><div><span>CASH FLOW</span><strong>{{ store.meta?.cashFlowStatementCount }} ROWS</strong></div></section>
    <LoadingState v-if="loading" /><ErrorState v-else-if="error" :code="error.code" :message="error.message" @retry="load" />
    <template v-else-if="data"><div class="content-grid"><section class="panel"><header class="panel-header"><h2>最近导入批次</h2></header><div class="table-scroll"><table><caption class="sr-only">最近导入批次</caption><thead><tr><th>批次</th><th>状态</th><th>原始</th><th>正式</th><th>问题</th></tr></thead><tbody><tr v-for="batch in data.batches" :key="batch.batchId"><td><strong>{{ batch.sourceName }}</strong><small>{{ batch.batchId }}</small></td><td><span class="status-pill">{{ batch.status }}</span></td><td>{{ batch.rawRowCount }}</td><td>{{ batch.normalizedRowCount }}</td><td>{{ batch.issueCount }}</td></tr></tbody></table></div></section><section class="panel quality-summary"><header class="panel-header"><h2>异常解释 · NULL ≠ ZERO</h2></header><p>质量问题主要记录原始字段为空或无法解析。正式表保留为 <code>NULL</code>，分析界面显示“暂无数据”，不会替换成 0。</p><dl><div><dt>覆盖公司</dt><dd>{{ store.meta?.companyCount }}</dd></div><div><dt>报告期间</dt><dd>{{ store.meta?.periodStart }}<br>— {{ store.meta?.periodEnd }}</dd></div><div><dt>数据库修改</dt><dd>{{ store.meta ? new Date(store.meta.modifiedAt).toLocaleString('zh-CN') : '—' }}</dd></div></dl></section></div>
      <section class="panel issues"><header class="panel-header"><div><h2>字段质量记录 · {{ data.issues.length }} 条</h2><p v-if="!data.issues.length">当前未发现标准化异常</p><p v-else>仅显示最近 200 条；原始值可用于回查采集页面</p></div></header><div v-if="data.issues.length" class="table-scroll"><table><caption class="sr-only">字段质量问题</caption><thead><tr><th>报表</th><th>公司 / 期间</th><th>字段</th><th>原始值</th><th>问题</th></tr></thead><tbody><tr v-for="(issue, index) in data.issues" :key="`${issue.code}-${issue.fieldName}-${index}`"><td>{{ issue.statementType }}</td><td>{{ issue.code ?? '—' }}<small>{{ issue.reportPeriod ?? '—' }}</small></td><td>{{ issue.fieldName }}</td><td>{{ issue.rawValue ?? 'NULL' }}</td><td><span class="issue-code">{{ issue.issueCode }}</span>{{ issue.issueMessage }}</td></tr></tbody></table></div></section>
    </template>
  </section>
</template>
<style scoped>
.source-ledger { display: grid; grid-template-columns: 2fr repeat(3, 1fr); margin-bottom: var(--space-md); }.source-ledger div { min-width: 0; padding: var(--space-md); border-right: var(--rule-thin) solid var(--color-rule); }.source-ledger div:last-child { border-right: 0; }.source-ledger span { display: block; color: var(--color-ink-faint); font: var(--text-xs) var(--font-data); }.source-ledger strong { display: block; overflow: hidden; margin-top: var(--space-xs); font: 600 var(--text-sm) var(--font-data); text-overflow: ellipsis; white-space: nowrap; }.panel-header p { margin: var(--space-2xs) 0 0; color: var(--color-ink-muted); font-size: var(--text-xs); }.quality-summary > p { padding: var(--space-lg); color: var(--color-ink-muted); }.quality-summary code { color: var(--color-accent); }.quality-summary dl { margin: 0; }.quality-summary dl div { display: flex; justify-content: space-between; padding: var(--space-sm) var(--space-lg); border-top: var(--rule-thin) solid var(--color-rule); }.quality-summary dt { color: var(--color-ink-muted); }.quality-summary dd { margin: 0; text-align: right; font-family: var(--font-data); }.issues { margin-top: var(--space-md); }td strong, td small { display: block; }.status-pill, .issue-code { display: inline-block; margin-right: var(--space-xs); padding: 0 var(--space-xs); border: var(--rule-thin) solid var(--color-rule-strong); color: var(--color-accent); font: var(--text-xs) var(--font-data); }@media (max-width: 760px) { .source-ledger { grid-template-columns: 1fr 1fr; }.source-ledger div:nth-child(2) { border-right: 0; } }
</style>
